---
- name: Gerar ARM template - network security groups
  template:
    src: "{{ role_path }}/template/network_security_group.j2"
    dest: /tmp/network_security_groups.json

- name: Deploy network security groups
  command: >
    az deployment group create
    --resource-group {{ (resource_data.values() | list | first).properties.resource_group }}
    --template-file /tmp/network_security_groups.json
    --name deploy-network-security-groups
