---
- name: Create Resource Groups
  include_role:
    name: azure
    tasks_from: create_resource_group
  when: resource_groups is defined

- name: Create Storage Accounts
  include_role:
    name: azure
    tasks_from: create_storage_account
  when: storage_accounts is defined

- name: Create Network Security Groups
  include_role:
    name: azure
    tasks_from: create_network_security_group
  when: network_security_groups is defined
